### ISSUE TITLE
HdfToSplunkViaS3 MVP

### ISSUE THREAD

**Issue by em-c-rod** [mitre/serverless-step-functions#1]
Create example step function to be triggered by an hdf file in an s3 bucket and send to splunk.
---
**TODO:**
- [x] Pass S3 contents to stepFunctions
- [x] Verify the result of stateMachine Execution output
- [x] Verify results in Splunk
- [x] ~~Configure `command_string` from `stateMachineTrigger` lambda to pass to `saf-lambda`~~
- [x] Lambda input - Pass private command data in as env variables
- [x] Update the `stateMachineTrigger` lambda function to process the correct file(s), in other words, investigate `event.Records[0]`. Test with multiple files in the bucket.
- [x] Fix SAF Lambda trigger so it is only called once (instead of twice). Test with s3:ObjectCreated:Put.
- [x] Add more role requirements for use by organizations (add `path`, and `permission boundary`).
- [x] Add documentation for use of this
- [x] Add updated diagram of the workflow
- [x] Refer to the specific resources.Resources for IAM permissions and remove `Resource: "*"` from all statements (example snippet below)
```
Resource:
  Fn::Join:
    - ''
    - - 'arn:aws:s3:::'
      - Ref: ServerlessDeploymentBucket
      - '/*'
```
---
**Enhancements:**
- [x] Find a way to add a trigger inside stepFunctions instead of Lambda (CloudWatch)
- [x] Accept s3 bucket name as an environment variable or generate it if not specified. s3 bucket-name: ${opt:stage}-${self:service}-sample-name (sample-name could be generated blah string)
- [x] Pass s3 object file contents to `saf-lambda` instead of s3 bucket name and file name.
- [x] Consider `Secrets Manager` for Splunk credentials

**Comment by karikarshivani** [comment]
All the action items are either completed, rendered irrelevant, or created as issues in the [saf-lambda-function](https://github.com/mitre/saf-lambda-function/issues) repo.
